# Generated by Django 4.1 on 2023-10-05 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_order_options_alter_orderitems_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="phone",
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
