# Generated by Django 4.1 on 2023-10-05 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_address_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address", name="phone", field=models.BigIntegerField(null=True),
        ),
    ]
