# Generated by Django 4.1 on 2023-10-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_address_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="image",
            field=models.ImageField(max_length=200, null=True, upload_to=""),
        ),
    ]
