# Generated by Django 3.2.1 on 2023-10-11 14:07

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20231011_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='MSILaptop.jpg', null=True, upload_to=core.models.user_directory_path),
        ),
    ]
