# Generated by Django 4.1 on 2023-10-05 02:23

from django.db import migrations, models
import userauth.models


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0002_follow"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(
                null=True, upload_to=userauth.models.user_directory_path
            ),
        ),
    ]
